'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("StahnkeFramework.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! jQuery v1.11.2 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        '''!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=&quot;1.11.2&quot;,m=function(a,b){return new m.fn.init(a,b)},n=/^[\s\uFEFF\xA [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_1_11_2_min() As String
            Get
                Return ResourceManager.GetString("jquery_1_11_2_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /// &lt;reference path=&quot;jquery-1.11.2.min.js&quot; /&gt;
        '''/// &lt;reference path=&quot;QueryBuilder.js&quot; /&gt;
        '''/// &lt;reference path=&quot;Main.js&quot; /&gt;
        '''
        '''function isNotNull(o) {
        '''    return (o != &apos;&apos; &amp;&amp; o != null &amp;&amp; o != &apos;undefined&apos;)
        '''}
        '''
        '''function AjaxPost(query, postData) {
        '''    return $.ajax({
        '''        url: query,
        '''        type: &apos;POST&apos;,
        '''        data: createQuery(postData),
        '''        cache: false,
        '''        processData: false,
        '''        contentType: &apos;application/json&apos;
        '''    });
        '''}
        '''
        '''function executeQuery(query, postData) {
        '''    return A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Main() As String
            Get
                Return ResourceManager.GetString("Main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /// &lt;reference path=&quot;jquery-1.11.2.min.js&quot; /&gt;
        '''/// &lt;reference path=&quot;QueryBuilder.js&quot; /&gt;
        '''/// &lt;reference path=&quot;Main.js&quot; /&gt;
        '''
        '''function QueryBuilder() {
        '''
        '''    var myBuilder = new Object();
        '''    var Entries = [];
        '''
        '''    function keyValueToQuery(newKey, newValue) {
        '''        return encodeURIComponent(newKey) + &apos;=&apos; + encodeURIComponent(newValue)
        '''    }
        '''
        '''    function combine(input, keyValuePair) {
        '''        return input + &apos;&amp;&apos; + keyValuePair
        '''    }
        '''
        '''    function appendEntry(input, newKey, newValue) {
        '''        v [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property QueryBuilder() As String
            Get
                Return ResourceManager.GetString("QueryBuilder", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
