'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Session
    Public Property SessionID As String
    Public Property SessionUser As String
    Public Property ExpiresOn As Date
    Public Property AutoRenewID As String
    Public Property RemoteHost As String
    Public Property PruneRequired As Byte

End Class
